# will be used as entry in DB to say SITE OFF/ON for healthcheck

server:
  port: 8443  
  tomcat:
      max-threads: 50

mso:
  infra:
    auditInventory: false
    default:
      versions:
        apiMinorVersion: 0
        apiPatchVersion: 0
    service:
      macro:
        default:
          testApi: GR_API
  avpn:
    bpel:
      uri: /mso/async/services/AVPNWorkflowActionBB
      timeout: 180
  camunda:
    rest:
      task:
        uri: /sobpmnengine/task
      history:
        uri: /sobpmnengine/history/process-instance?variables=mso-request-id_eq_
                
spring:
  datasource:
    hikari:
      jdbcUrl: jdbc:mariadb://${DB_HOST}:${DB_PORT}/catalogdb
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
      pool-name: catdb-pool
      registerMbeans: true
  jpa:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: validate
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        enable-lazy-load-no-trans: true
  jersey:
    type: filter
                       
request:
  datasource:
    hikari:
      jdbcUrl: jdbc:mariadb://${DB_HOST}:${DB_PORT}/requestdb
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
      pool-name: reqdb-pool
      registerMbeans: true
#Actuator
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
  metrics:
    se-global-registry: false
    export:
      prometheus:
        enabled: true # Whether exporting of metrics to Prometheus is enabled.
        step: 1m # Step size (i.e. reporting frequency) to use.
 

org:
  onap:
    so:
      adapters:
        network:
          encryptionKey: aa3871669d893c7fb8abbcda31b88b4f
